

let  obj = [
    1,
    [
        "aaecpdLyjvZBwrvm+cedCcQy",
        "6dp886tohOX6jJSAT5jEac",
        "20nzYU7whGo5BIzI0nwLow",
        "22ZXI6FkdA2rQAcI69aTCd",
        "a2MjXRFdtLlYQ5ouAFv/+R",
        "1brCQlP99LM6S3pv3mpb+b",
        "89e8jSLX9FioZKxOvQ4G8K",
        "fdxvsse5ZAFpo52s8zrCwC",
        "2a0GdtCmpH5bxy4CIoS0Mm",
        "bf5L2P9zFL/J2uyho42iMh",
        "bezKvB6kRNR4+HnU0mIsxa",
        "8bO/Ed9NpIOYiHfMALMPVm",
        "e9HLa71u9Os7RzoWAhYQO3",
        "26BWcWY9FAzJ2XjI/XcuVq"
    ],
    [
        "node",
        "_textureSetter",
        "_spriteFrame",
        "root",
        "data",
        "wo_hu_cang_long",
        "ru_he_tian_yi",
        "hu_hu_sheng_wei"
    ],
    [
        "cc.SpriteFrame",
        [
            "cc.Node",
            [
                "_name",
                "_opacity",
                "_components",
                "_prefab",
                "_contentSize",
                "_trs",
                "_parent",
                "_children",
                "_color"
            ],
            1,
            9,
            4,
            5,
            7,
            1,
            2,
            5
        ],
        [
            "cc.Widget",
            [
                "_alignFlags",
                "_left",
                "_right",
                "_top",
                "_bottom",
                "_originalWidth",
                "_originalHeight",
                "node"
            ],
            -4,
            1
        ],
        [
            "cc.PrefabInfo",
            [
                "fileId",
                "root"
            ],
            2,
            1
        ],
        [
            "cc.Sprite",
            [
                "_sizeMode",
                "node",
                "_materials",
                "_spriteFrame"
            ],
            2,
            1,
            3,
            6
        ],
        [
            "cc.Prefab",
            [
                "_name"
            ],
            2
        ],
        [
            "7f73dj8mYJEnaiDUvzN6gLn",
            [
                "node",
                "wo_hu_cang_long",
                "ru_he_tian_yi",
                "hu_hu_sheng_wei"
            ],
            3,
            1,
            6,
            6,
            6
        ],
        [
            "cc.BlockInputEvents",
            [
                "node"
            ],
            3,
            1
        ],
        [
            "cc.Button",
            [
                "zoomScale",
                "_N$transition",
                "node"
            ],
            1,
            1
        ],
        [
            "cc.Label",
            [
                "_string",
                "_fontSize",
                "_lineHeight",
                "_styleFlags",
                "_N$horizontalAlign",
                "_N$verticalAlign",
                "node",
                "_materials"
            ],
            -3,
            1,
            3
        ]
    ],
    [
        [
            3,
            0,
            1,
            2
        ],
        [
            1,
            0,
            6,
            2,
            3,
            4,
            5,
            2
        ],
        [
            4,
            1,
            2,
            3,
            1
        ],
        [
            5,
            0,
            2
        ],
        [
            1,
            0,
            7,
            2,
            3,
            4,
            5,
            2
        ],
        [
            1,
            0,
            1,
            6,
            2,
            3,
            8,
            4,
            3
        ],
        [
            1,
            0,
            6,
            7,
            2,
            3,
            4,
            5,
            2
        ],
        [
            2,
            0,
            7,
            2
        ],
        [
            2,
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8
        ],
        [
            6,
            0,
            1,
            2,
            3,
            1
        ],
        [
            3,
            1,
            1
        ],
        [
            4,
            0,
            1,
            2,
            3,
            2
        ],
        [
            7,
            0,
            1
        ],
        [
            8,
            0,
            1,
            2,
            3
        ],
        [
            9,
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            7
        ]
    ],
    [
        [
            [
                {
                    "name": "bg",
                    "rect": [
                        0,
                        0,
                        677,
                        991
                    ],
                    "offset": [
                        0,
                        0
                    ],
                    "originalSize": [
                        677,
                        991
                    ],
                    "capInsets": [
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ],
            [
                0
            ],
            0,
            [
                0
            ],
            [
                1
            ],
            [
                2
            ]
        ],
        [
            [
                {
                    "name": "b",
                    "rect": [
                        0,
                        0,
                        929,
                        628
                    ],
                    "offset": [
                        0,
                        0
                    ],
                    "originalSize": [
                        929,
                        628
                    ],
                    "capInsets": [
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ],
            [
                0
            ],
            0,
            [
                0
            ],
            [
                1
            ],
            [
                3
            ]
        ],
        [
            [
                [
                    3,
                    "Jie_Guo_1"
                ],
                [
                    4,
                    "Jie_Guo_1",
                    [
                        -4,
                        -5,
                        -6,
                        -7,
                        -8
                    ],
                    [
                        [
                            7,
                            45,
                            -2
                        ],
                        [
                            9,
                            -3,
                            11,
                            12,
                            13
                        ]
                    ],
                    [
                        10,
                        -1
                    ],
                    [
                        5,
                        750,
                        1624
                    ],
                    [
                        375,
                        812,
                        0,
                        0,
                        0,
                        0,
                        1,
                        1,
                        1,
                        1
                    ]
                ],
                [
                    5,
                    "gray",
                    180,
                    1,
                    [
                        [
                            11,
                            0,
                            -9,
                            [
                                0
                            ],
                            1
                        ],
                        [
                            8,
                            45,
                            -375,
                            -375,
                            -812,
                            -812,
                            100,
                            100,
                            -10
                        ],
                        [
                            12,
                            -11
                        ]
                    ],
                    [
                        0,
                        "5axGNOOX1MKq6u9S/bpHko",
                        1
                    ],
                    [
                        4,
                        4278190080
                    ],
                    [
                        5,
                        1500,
                        3248
                    ]
                ],
                [
                    6,
                    "title",
                    1,
                    [
                        -13
                    ],
                    [
                        [
                            2,
                            -12,
                            [
                                7
                            ],
                            8
                        ]
                    ],
                    [
                        0,
                        "19VsXFSXNPPoNvjkwJL212",
                        1
                    ],
                    [
                        5,
                        929,
                        628
                    ],
                    [
                        0,
                        438.593,
                        0,
                        0,
                        0,
                        0,
                        1,
                        1,
                        1,
                        1
                    ]
                ],
                [
                    1,
                    "can_yu_chou_jiang_an_niu",
                    1,
                    [
                        [
                            2,
                            -14,
                            [
                                9
                            ],
                            10
                        ],
                        [
                            13,
                            0.95,
                            3,
                            -15
                        ]
                    ],
                    [
                        0,
                        "98q8HJRYdADK8k80UR1CMz",
                        1
                    ],
                    [
                        5,
                        337,
                        152
                    ],
                    [
                        3.061,
                        -622.755,
                        0,
                        0,
                        0,
                        0,
                        1,
                        1,
                        1,
                        0
                    ]
                ],
                [
                    1,
                    "bg",
                    1,
                    [
                        [
                            2,
                            -16,
                            [
                                2
                            ],
                            3
                        ]
                    ],
                    [
                        0,
                        "b7P4z+N8JKrZDa6303kAR+",
                        1
                    ],
                    [
                        5,
                        677,
                        991
                    ],
                    [
                        10.006,
                        -167.204,
                        0,
                        0,
                        0,
                        0,
                        1,
                        1,
                        1,
                        1
                    ]
                ],
                [
                    1,
                    "content",
                    1,
                    [
                        [
                            2,
                            -17,
                            [
                                4
                            ],
                            5
                        ]
                    ],
                    [
                        0,
                        "946u5YA/9ErKu+GsQ6zKTW",
                        1
                    ],
                    [
                        5,
                        850,
                        1058
                    ],
                    [
                        0,
                        -239.347,
                        0,
                        0,
                        0,
                        0,
                        1,
                        1,
                        1,
                        1
                    ]
                ],
                [
                    1,
                    "score",
                    3,
                    [
                        [
                            14,
                            "600",
                            600,
                            600,
                            1,
                            1,
                            1,
                            -1,
                            [
                                6
                            ]
                        ]
                    ],
                    [
                        0,
                        "41mpcYqXpN8YWVsd4oGXlx",
                        1
                    ],
                    [
                        5,
                        100.11,
                        75.6
                    ],
                    [
                        69.455,
                        -266.022,
                        0,
                        0,
                        0,
                        0,
                        1,
                        1,
                        1,
                        1
                    ]
                ]
            ],
            0,
            [
                0,
                3,
                1,
                0,
                0,
                1,
                0,
                0,
                1,
                0,
                -1,
                2,
                0,
                -2,
                5,
                0,
                -3,
                6,
                0,
                -4,
                3,
                0,
                -5,
                4,
                0,
                0,
                2,
                0,
                0,
                2,
                0,
                0,
                2,
                0,
                0,
                3,
                0,
                -1,
                7,
                0,
                0,
                4,
                0,
                0,
                4,
                0,
                0,
                5,
                0,
                0,
                6,
                0,
                0,
                7,
                0,
                4,
                1,
                18
            ],
            [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            [
                -1,
                2,
                -1,
                2,
                -1,
                2,
                -1,
                -1,
                2,
                -1,
                2,
                5,
                6,
                7
            ],
            [
                0,
                4,
                0,
                5,
                0,
                6,
                0,
                0,
                1,
                0,
                7,
                1,
                8,
                9
            ]
        ],
        [
            [
                {
                    "name": "a",
                    "rect": [
                        0,
                        0,
                        929,
                        628
                    ],
                    "offset": [
                        0,
                        0
                    ],
                    "originalSize": [
                        929,
                        628
                    ],
                    "capInsets": [
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ],
            [
                0
            ],
            0,
            [
                0
            ],
            [
                1
            ],
            [
                10
            ]
        ],
        [
            [
                {
                    "name": "content",
                    "rect": [
                        0,
                        0,
                        850,
                        1058
                    ],
                    "offset": [
                        0,
                        0
                    ],
                    "originalSize": [
                        850,
                        1058
                    ],
                    "capInsets": [
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ],
            [
                0
            ],
            0,
            [
                0
            ],
            [
                1
            ],
            [
                11
            ]
        ],
        [
            [
                {
                    "name": "c",
                    "rect": [
                        0,
                        0,
                        929,
                        628
                    ],
                    "offset": [
                        0,
                        0
                    ],
                    "originalSize": [
                        929,
                        628
                    ],
                    "capInsets": [
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ],
            [
                0
            ],
            0,
            [
                0
            ],
            [
                1
            ],
            [
                12
            ]
        ],
        [
            [
                {
                    "name": "e",
                    "rect": [
                        0,
                        0,
                        337,
                        152
                    ],
                    "offset": [
                        -0.5,
                        0
                    ],
                    "originalSize": [
                        338,
                        152
                    ],
                    "capInsets": [
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ],
            [
                0
            ],
            0,
            [
                0
            ],
            [
                1
            ],
            [
                13
            ]
        ]
    ]
]

$done({ body: JSON.stringify(obj) });